# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/sybrin-innovations/Sybrin.iOS.Pods.git'

target 'IdentityExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdentityExample
  pod 'Sybrin.iOS.Identity'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
  end
 end
end